### ISSUE TITLE
TypeError: list indices must be integers, not str

### ISSUE THREAD

**Issue by Sandeepsr** [minimaxir/facebook-page-post-scraper#16]
test_results is a list below one:
test_status = getFacebookPageFeedData(page_id, access_token, 1)["data"][0]

Your next function below, expect this to be dictionary and though an error :TypeError: list indices must be integers, not str

def processFacebookPageFeedStatus(status)

**Comment by minimaxir** [comment]
ATM, I'm not making changes to the code in the notebook since it's obsolete.
