### ISSUE TITLE
Resulting CSV format error

### ISSUE THREAD

**Issue by enod** [minimaxir/facebook-page-post-scraper#17]
When writing to CSV file, it loses it's format. For example following should be in 1 line if I'm not wrong but : 
156915824368931_1104005622993275,"Example :

06:00 bla
06:30 bla
09:30 bla
10:00 bla
10:30 bla
11:40 bla
12:00 bla
13:40 bla
15:30 bla
19:00 bla
20:30 bla
22:30 bla
23:40 bla
00:30 bla
02:00 bla,,status,,2016-07-04 06:02:16,34,27,1,30,0,0,0,0,4

I can write script which solves this problem(put all in 1 line per entry) but is there anyway to solve this when writing to CSV file?

**Comment by minimaxir** [comment]
If you are referring to the fact that `status_message` can have line breaks, that is intentional, as Facebook Posts can have line spaces, and any workarounds (e.g. converting line breaks to `\n`) would break import.

This should not cause any issues with CSV use cases.
