### ISSUE TITLE
HTTP error 400

### ISSUE THREAD

**Issue by omarajmeri** [minimaxir/facebook-page-post-scraper#18]
I keep getting this error - tried several different pages but no luck. any idea why?

**Comment by minimaxir** [comment]
HTTP error 400 is a Bad Request, which means either your App ID or App Secret are incorrect. Can you double check?

**Comment by iblind** [comment]
Hey Max, was there any more on this front? I had something similar happen today:

> XXX Comments Processed: 2016-09-07 14:29:15.632319
> HTTP Error 400: Bad Request
> Error for URL https://graph.facebook.com/v2.6/10153459535612217_10153459625697217/comments?fields=id,message,like_count,created_time,comments,from,attachment&order=chronological&limit=100&access_token=<APP|TOKEN>: 2016-09-07 14:29:26.333514
> Retrying.
> Traceback (most recent call last):
>   File "get_fb_comments.py", line 173, in <module>
>     scrapeFacebookPageFeedComments(file_id, access_token)
>   File "get_fb_comments.py", line 125, in scrapeFacebookPageFeedComments
>     for subcomment in subcomments['data']:
> TypeError: 'NoneType' object has no attribute '__getitem__'
>

**Comment by minimaxir** [comment]
Thanks for providing the stack trace. I'm not 100% sure what happening, but it may be possible to add safeguards. Looking into it.

**Comment by iblind** [comment]
Think I've figured out what's up. FB seems to indicate that there are comments at time when there may not be, so all this would require is an 
` if 'data' in subcomments:`
statement prior to the loop, just like you had set up in the following section.

This is actually something that came up for me in line 66-
`comment_author = unicode_normalize(comment['from']['name'])`
which has previously led to `KeyError: 'name' `

This looks like it can be solved by changing that line to 

`comment_author = '' if 'name' not in comment['from'] else \
                    unicode_normalize(comment['from']['name'])`


Can submit a pull request in a little bit for you to review?
