### ISSUE TITLE
Your script is great!!!

### ISSUE THREAD

**Issue by vinhquy** [minimaxir/facebook-page-post-scraper#22]
Hi Minimaxir,

Thank you so much for the great script that you have created. I have some questions and would be highly appreciated if you can provide me some guidance on how to modify the script.
1. The current script does not support Unicode font (Vietnamese)
2. How can I limit number of posts to new posts in a fanpage within 24 hours?
3. How can I scrap posts from many fan pages at a same time. I have more than 50 pages need to scrap data and I do scrap daily. So repeating one process for 50 times is time consuming for me.

Thank you so much,
Quy

**Comment by minimaxir** [comment]
1. Working into fixing unicode.
2. You'll need to add an `until` parameter and set that to current time - 24 hours.
3. Modify the script to take in a command-line argument for `page_id`, then use a wrapper to run that.

All are outside scope of this implementation.

**Comment by PhanDuc** [comment]
Thanks minimaxir !

**Comment by vinhquy** [comment]
Hi minimaxir,
Thank you so much.
