### ISSUE TITLE
Database question

### ISSUE THREAD

**Issue by andravasile** [minimaxir/facebook-page-post-scraper#37]
Hello again :)

Do you have any suggestions about how to modify the code from get_fb_posts_fb_page (2.7 version) in order to save the CSV files into a database?

Thank you in advance!

**Comment by popstick** [comment]
I modified the script to save to mysql database. Also added a scheduler. It might be a bit of a mess, It was a while ago.
https://github.com/popstick/facebook-page-post-scraper
