### ISSUE TITLE
Cutting off scrape after a certain date?

### ISSUE THREAD

**Issue by tarosenblut** [minimaxir/facebook-page-post-scraper#38]
Is it possible to alter the code so that, for example, the scraper stops pulling after a certain period in time? Given that some pages have been around for years, I might only want 2017 and 2016 posts on a page. Is there a way to say "if year is 2015" stop pulling posts?

**Comment by dizwe** [comment]
I pulled requests  in terms of this issue. I don't know whether minimaxir merge it or not, somehow have a look.

**Comment by minimaxir** [comment]
Now implemented.
