### ISSUE TITLE
Getting *all* posts from a page.

### ISSUE THREAD

**Issue by Ward9250** [minimaxir/facebook-page-post-scraper#39]
I'm doing a project analysing data and ideally I want to collect *all* posts from a Facebook page. But I know the FB graph API has a limit of 100.
I was wondering whether using pagination as in the get_fb_posts_fb_page.py file either:
(1) Ensures all posts going back in time get collected.
Or
(2) Navigates through different pages and gets only the first 100 posts from each page.

**Comment by minimaxir** [comment]
The scraper goes as far back as possible until it can't go any further.
