### ISSUE TITLE
GET request to 'nytimes' leads to SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by meet90** [minimaxir/facebook-page-post-scraper#4]
I am a beginner and this might be a dumb question.
When I make a GET request to nytimes, I get this error:

```urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>```

I have tried running my query on Facebook Graph API explorer, but it works perfectly well there.
Is there something I am missing?

**Comment by minimaxir** [comment]
That is likely not an issue with the script and more likely a [Python configuration issue](http://stackoverflow.com/questions/27835619/ssl-certificate-verify-failed-error).

**Comment by meet90** [comment]
Thanks, it does seem a configuration issue. I messed up Python on my system while trying to install Django. Will have to search more for solutions!
