### ISSUE TITLE
Facebook search support?

### ISSUE THREAD

**Issue by peeter-t2** [minimaxir/facebook-page-post-scraper#41]
Hey! Do you think this could be adapted to run through all public posts on some keyword? FB currently at least allows scrolling through them.

E.g. https://www.facebook.com/search/str/search%2Bterm/keywords_search?filters_rp_author=public-feed

Thanks for the app again! :)

**Edit:** Or maybe with something like this just to decrease the number of posts scraped if looking for something particular.: https://graph.facebook.com/nytimes/search?q=keyword_here&type=post

Link example here: https://www.facebook.com/search/str/politics/keywords_search?filters_rp_author=134486075205

**Comment by minimaxir** [comment]
The search API endpoint  is a different endpoint and if Facebook allowed programmatic public search on that end point, literally everyone would use it.

Not much I can do on my end though.

**Comment by peeter-t2** [comment]
Thanks. Indeed they would, too bad they've removed the much used feature then. :) Best!
