### ISSUE TITLE
ERROR 404

### ISSUE THREAD

**Issue by lukaskris** [minimaxir/facebook-page-post-scraper#48]
> Scraping cnn Facebook Page: 2017-05-17 20:22:00.719000
> 
> HTTP Error 400: Bad Request
> Error for URL https://graph.facebook.com/v2.9/cnn/posts/?limit=100&access_token=<FILL IN>|<FILL IN>&fields=message,link,created_time,type,name,id,comments.limit(0).summary(true),shares,reactions.limit(0).summary(true): 2017-05-17 20:22:06.220000
> Retrying.
> HTTP Error 400: Bad Request
> Error for URL https://graph.facebook.com/v2.9/cnn/posts/?limit=100&access_token=<FILL IN>|<FILL IN>&fields=message,link,created_time,type,name,id,comments.limit(0).summary(true),shares,reactions.limit(0).summary(true): 2017-05-17 20:22:11.563000
> Retrying.
> HTTP Error 400: Bad Request
> 

anyone please help,
i think trouble with access_token

**Comment by minimaxir** [comment]
Make sure you fill in the `app_id` and the `app_secret` as noted in the instructions.

**Comment by lukaskris** [comment]
yes thankyou the error was solved
but i want fetch from user not from page id
but the return json just

> {
   

> "data": [
>       
>    ]
> }

**Comment by minimaxir** [comment]
Correct, you cannot fetch user data this way. It will only work on Facebook Pages/Groups.

**Comment by lukaskris** [comment]
sir, i'm trying using Access_token for user, not using Access_token from app_id|secret_key
i'm try fetch post from user with id Facebook, and good return json from status
but if i'm using id from not in my friendlist, json not return null data
can you help me what's wrong from facebook
