### ISSUE TITLE
carriage return should be escaped if in the content

### ISSUE THREAD

**Issue by cdhit** [minimaxir/facebook-page-post-scraper#50]
I found that "carriage return" should be escaped in the content otherwise the single row of data will be split  into different rows. 

But I can use'\r' to identify the newline, not sure if this is an issue.

**Comment by minimaxir** [comment]
The carriage returns are encoded in a way that a `read_csv` command or Excel will be able to interpret them.

If you are scanning the output line-by-line, that is not a typical case.
