### ISSUE TITLE
Scrap comment of a specific post

### ISSUE THREAD

**Issue by quyleanh** [minimaxir/facebook-page-post-scraper#53]
In the previous version, there is a option for scrap comment of s specific post.
`#reader = [dict(status_id='167994586682731_804458666369650')]`
How about in latest one? Thank you!

**Comment by minimaxir** [comment]
That wasn't an *intentional* option, just a quick way to QA the script.

If there is interest in a single-status retrieval, I can add that. (should be mostly the same)

**Comment by quyleanh** [comment]
@minimaxir could you please? I really want this option. Thank you!

**Comment by quyleanh** [comment]
@minimaxir could you please update the repo for this issue? Thank you very much!

**Comment by alxbgmz** [comment]
I would love this feature too

**Comment by minimaxir** [comment]
Added option to query a single status. (you'll still need to extract the `status_id` via another scraper)
