### ISSUE TITLE
limit end date for scraping

### ISSUE THREAD

**Issue by ezaratemx** [minimaxir/facebook-page-post-scraper#55]
Hi, 

is there a way to stop scraping at a certain date ?

**Comment by Mika15** [comment]
hi,
it also concerns me

**Comment by ezaratemx** [comment]
parameters = "/?limit={}&since=2017-04-13&access_token={}".format(100, access_token)

**Comment by iamrajeshchauhan** [comment]
for the best result to scrap the data use this 

parameters = "/?limit={}&since=2017-04-13until= 2017-04-30&access_token={}".format(100, access_token)

this is amazing to make bucket the dates.

**Comment by minimaxir** [comment]
Added since/until in https://github.com/minimaxir/facebook-page-post-scraper/commit/0eae2ef7a090b2d74c3f43bb85f02cd01585b9a3
