### ISSUE TITLE
I get an error

### ISSUE THREAD

**Issue by eshinesimida** [minimaxir/facebook-page-post-scraper#56]
Traceback (most recent call last):

  File "<ipython-input-147-0badb2c96963>", line 173, in <module>
    scrapeFacebookPageFeedStatus(page_id, access_token)

  File "<ipython-input-147-0badb2c96963>", line 154, in scrapeFacebookPageFeedStatus
    w.writerow(status_data + reactions_data)

UnicodeEncodeError: 'gbk' codec can't encode character '\u2022' in position 69: illegal multibyte sequence

**Comment by quyleanh** [comment]
@eshinesimida in `open `function add more parameters: `encoding='utf-8'`

**Comment by eshinesimida** [comment]
Thank you

**Comment by quyleanh** [comment]
If your problem is solved, please close it.
