### ISSUE TITLE
I need your help

### ISSUE THREAD

**Issue by eshinesimida** [minimaxir/facebook-page-post-scraper#57]
I get 'https://www.facebook.com/pg/cnn/posts/' from cnn news in facebook , and base_url = "https://graph.facebook.com/v2.9/cnn/posts/?limit=100&access_token=1407412942683680|rKwGpQjFSaW-HVcoBC5gch8XNwU", how do you get it,

I want the website "https://www.facebook.com/search/posts/?q=hong%20kong"  in hong kong from facebook , I finally get the base_url . Would you help me ?  Thank you

**Comment by quyleanh** [comment]
This script need a specific page or group id. You can't enter link like that.

**Comment by minimaxir** [comment]
You can't scrape the /search endpoint. (otherwise everyone would do it)
