### ISSUE TITLE
Count reactions by type

### ISSUE THREAD

**Issue by liisilaineste** [minimaxir/facebook-page-post-scraper#6]
Can you count reactions separate columns by type, so LIKE, WOW, SAD etc would be separate counts? Thank you!

**Comment by minimaxir** [comment]
I wish. :(

**Comment by liisilaineste** [comment]
fixed in a fork https://github.com/Digitaalhumanitaaria/facebook-page-post-scraper/commit/8748c9ce807ab2ff121f450b44a0641f7f6b0573

**Comment by minimaxir** [comment]
Huh, I *swear* the 'type' parameter was not documented when I first updated in April.

Easy fix. Will do tonight. (And give proper credit to linked Repo)

**Comment by minimaxir** [comment]
Updated with b49ec2f0a44f1ea0c40baf5e628bc125dbf7197c

Let me know if that works for you.
