### ISSUE TITLE
Youtube Video comments

### ISSUE THREAD

**Issue by ankyj268** [minimaxir/facebook-page-post-scraper#72]
Hi,

Can we fetch video comments, likes and views using python or R?

\ankyj268

**Comment by minimaxir** [comment]
This is out of scope for this project, but the [YouTube Data API](https://developers.google.com/apis-explorer/#p/youtube/v3/youtube.commentThreads.list?part=snippet%252Creplies&maxResults=100&videoId=wtLJPvx7-ys&_h=1&) allows you to fetch YouTube data (to a degree; YouTube does pagenation shenanigans which makes things harder)
