### ISSUE TITLE
Blank rows between observations in CSV export? 

### ISSUE THREAD

**Issue by dsynkov** [minimaxir/facebook-page-post-scraper#80]
Is anyone getting blank rows in the CSV export for any of the scrapers (i.m. seeing these for all three -- Comments, Page Status Updates, and Group Status Updates). There is a blank row in between each observation. This is an easy fix in Excel or if I'm re-importing an export as a dataframe, but I'm wondering if anyone has found a fix using the CSV writer already in the code. Thanks.

**Comment by gielk** [comment]
same issue

**Comment by kasamoh** [comment]
Hi , 
Just use **file = open('%s_file_name.csv' % page_id, 'w',newline='')**  instead of **file = open('%s_file_name.csv' % page_id, 'w')** 
( I added newline='' ) . 
Hope it helps . 
Regards

**Comment by dsynkov** [comment]
Thanks @kasamoh, this worked for me.
