### ISSUE TITLE
something like this coming on cmd

### ISSUE THREAD

**Issue by hemangpar** [minimaxir/facebook-page-post-scraper#93]
![image](https://user-images.githubusercontent.com/35444803/35085711-e473ddb2-fc4f-11e7-9068-7a68939cd102.png)

**Comment by hemangpar** [comment]
help

**Comment by SpangleLabs** [comment]
This looks the same as https://github.com/minimaxir/facebook-page-post-scraper/issues/74

**Comment by hemangpar** [comment]
@joshcoales thanks, buddy. It worked.
